version: "3.1"

services:
  pingfederate-a:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/tguy-ping/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-fedhub/pingfederate-a
    env_file:
      - ~/.pingidentity/devops
    volumes:
      - pingfederate-a-out:/opt/out
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
    
  pingfederate-b:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/tguy-ping/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-fedhub/pingfederate-b
    env_file:
      - ~/.pingidentity/devops
    volumes:
      - pingfederate-b-out:/opt/out
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 8031:9031
      - 8999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/tguy-ping/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pf-fedhub/pingdirectory
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
    
networks:
    pingnet-internal:
    pingnet-dmz:
    
volumes:
  pingfederate-a-out:
  pingfederate-b-out: